[project]
name = "vorm-tekenen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.7",
    "streamlit>=1.51.0",
]
